name = "day_01"
description = "Day 1 of Advent of Code 2025"
version = "0.1.0-dev"

authors = ["Diego Alonso Alvarez"]
maintainers = ["Diego Alonso Alvarez <d.alonso-alvarez@imperial.ac.uk>"]
maintainers-logins = ["dalonsoa"]

executables = ["day_01"]
